### ISSUE TITLE
Multi-arch container with arm/v7 and arm/64

### ISSUE THREAD

**Issue by bnhf** [gregewing/apcupsd#2]
@gregewing 

Any reason the container couldn't be built multi-arch? I have 6 APC UPS units, half of which I'm monitoring using apcupsd with nearby PCs. The other half are in locations where deploying a Raspberry Pi seems like about the best best for adding monitoring -- and I do everything I can using Docker these days. :-)

In addition to monitoring each of my UPS units using system tray icons:

![Screenshot 2023-01-15 131915](https://user-images.githubusercontent.com/41088895/212564890-20d1819a-1e99-444c-82d0-68dd34e6179a.png)

I'd also like to be able to pull up a Docker-based Grafana Dashboard like this:

![image](https://user-images.githubusercontent.com/41088895/212565006-dda80e43-e581-4168-808c-0f2fc9123d9e.png)

But that's in the future, right now I'd like to just get this running under the 64-bit version of the Raspberry Pi OS with Docker.

**Comment by gregewing** [comment]
Hi.  I'll look into that for you.  should not be to difficult to built for Pi.   As the the Grafana dashboard, I specifically built that image to pump data to Graphite, so I could then pull it our of Graphite with Grafana and make pretty dashboards.  I actually use a separate container with collectd running in it to capture data from the apcupsd container and pass it to Graphite.

**Comment by gregewing** [comment]
Hi.  I have built and published the container in a few additional flavours ( arm64 and armv7 )   I have not tested these yet, so your mileage may vary, but I invite you to test them out and let me know if you have any problems, or if you need a specific arm architecture to be supported, just let me know and I'll look into it.

**Comment by bnhf** [comment]
Great -- thanks! I'll give it a try, and let you  know how it works out.

**Comment by bnhf** [comment]
Looking on Docker Hub, all of the container tags appear to reference the same amd/64 container. Something's not quite right I think.

**Comment by gregewing** [comment]
Yeah I did some tests with a pi I have here and had problems. I will keep working on it.

Thanks and Regards
Greg Ewing
________________________________

**Comment by gregewing** [comment]
Made a little progress, I believe the images are now built to the correct architectures, only one i'm struggling with is armv6 ( to match my Pi for testing).   Please try them out and let me know if you have any more success with these builds.     You should be able to just pull the gregewing/apcupsd:latest image regardless of platform.   I'll see about deleting the other tags.

**Comment by bnhf** [comment]
@gregewing 

Nice work on the multi-arch container. I've pulled it for use on a Raspberry Pi 4 running the arm64 version of the Raspberry Pi OS, and it's working great. Also, I submitted a PR to update the ReadME to include a docker-compose example. Many thanks!
