### ISSUE TITLE
Quick dumb question - how do I monitor this?

### ISSUE THREAD

**Issue by Ryland0** [gregewing/apcupsd#8]
I have the container up and running. I opted for the volume over bind mount (that didn't seem to work). At this point, I just do not know if its doing the job. What is the proper way to monitor status? I tired apcaccess but received Connection refused.

Thank you.

**Comment by gregewing** [comment]
You can log in to the running container with "docker exec -it <congtainer_name> sh" and run apcaccess and it will dump the status of the UPS. This should let you know if it's talking to the UPS, or a master instance of apcupsd.

**Comment by Ryland0** [comment]
![image](https://github.com/gregewing/apcupsd/assets/36310715/ebfe8344-61df-489c-b73b-3a0877188bf3)
![image](https://github.com/gregewing/apcupsd/assets/36310715/f63f443d-51a1-47e8-b909-f44783a33fdf)

Thank you for your response. Your suggestion is what I've attempted to do, with the error shown.

**Comment by gregewing** [comment]
Looks to me like an incorrect config in the config file. It should not be connecting to localhost, that would be weird. Either connect to a remote instance of apcupsd, or to the locally attached UPS via a USB cable or similar.

**Comment by Ryland0** [comment]
I haven't touched the config. I did turn off the NETSERVER with an EV. Would that make a difference?

version: '3.8'
services:
  app:
    container_name: apcmon
    image: gregewing/apcupsd:latest
    devices:
      - /dev/usb/hiddev0
    environment:
      - TZ=America/New_York
      - UPSNAME=APC1300
      - NETSERVER=off
    restart: unless-stopped
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - apcmon:/etc/apcupsd
    hostname: apcmon
    domainname: noplacelike.home
    dns: '10.47.20.100'
    networks:
      macvlan:
        ipv4_address: '10.47.20.114'
    ports:
      - '3551:3551/tcp'
networks:
  macvlan:
    external: true
    name: macvlan
volumes:
  apcmon:
    external: true

**Comment by Ryland0** [comment]
Or would this do it? 
![image](https://github.com/gregewing/apcupsd/assets/36310715/a84cb38c-06a8-4388-9b5c-9a646c34979a)
Thank you again for your help.

**Comment by gregewing** [comment]
The best advice I can give right now is to read the manual. There is a link at the bottom of the docker hub page to the apcupsd manual pages. That will guide you through how to setup the config file. It's heavy reading at some points, but important to get it right.

**Comment by gregewing** [comment]
I'd help more, but I'm camping for the week and don't have great signal.

**Comment by Ryland0** [comment]
No worries. Enjoy your holiday.

**Comment by gregewing** [comment]
Hey Ryland0, just wanted to check if you managed to get it up and running, or if you are still having problems.  I wont be insulted if you switched to a different image either :-)

**Comment by Ryland0** [comment]
Turns out the serial to USB cable is bad and I'm not interested in the $40US APC wants to replace it. Thank you for checking up.

**Comment by gregewing** [comment]
Ah,  got you.

I bought a cheap non-original mine from Amazon for £8. Works like a charm.

Thanks and Regards
Greg Ewing
________________________________
