### ISSUE TITLE
`mail: not found` in log output

### ISSUE THREAD

**Issue by mtsardakas** [gregewing/apcupsd#9]
Hello and many thanks for your work! I'm wondering if it's known that the mail functionality isn't working - if yes, can I have a go at adding it?

**Comment by gregewing** [comment]
By all means do a pull request and request a merge. :)

Thanks and Regards
Greg Ewing
________________________________
From: Michael Tsardakas ***@***.***>
Sent: Tuesday, September 26, 2023 8:22:19 PM
To: gregewing/apcupsd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gregewing/apcupsd] `mail: not found` in log output (Issue #9)


Hello and many thanks for your work! I'm wondering if it's known that the mail functionality isn't working - if yes, can I have a go at adding it?

**Comment by gregewing** [comment]
To be fair though, it's more likely to be a config file thing, or a missing package.

Thanks and Regards
Greg Ewing
________________________________
From: Michael Tsardakas ***@***.***>
Sent: Tuesday, September 26, 2023 8:22:19 PM
To: gregewing/apcupsd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gregewing/apcupsd] `mail: not found` in log output (Issue #9)


Hello and many thanks for your work! I'm wondering if it's known that the mail functionality isn't working - if yes, can I have a go at adding it?

**Comment by gregewing** [comment]
Hi mtsardakas,  Just wanted to check if you managed to get this up and running, or are you still having problems ?

**Comment by mtsardakas** [comment]
Hi! I abandoned it in favor of adding a Pushover-based notification.
